# Generated by Django 4.0 on 2022-01-11 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paises_ciudades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelo',
            new_name='Pais',
        ),
    ]
